### ISSUE TITLE
Installation for Mac 

### ISSUE THREAD

**Issue by paulaferez** [JanMarvin/nlsur#8]
Hi marvin,
I'm having trouble installing the package in R Studio for Mac. I've already tried via drat and devtools.
Do you have any tips?
Best regards,

**Comment by JanMarvin** [comment]
Hi @paulaferez ,

thanks for raising the issue. Drat might be a little outdated, I shall remove the link if there is any. You should be able to install it from source - depending that you have xcode build tools for R enabled. Otherwise you can have a look at the [r-universe page](https://janmarvin.r-universe.dev/nlsur).

Best, Marvin

**Comment by JanMarvin** [comment]
I've updated the readme - mainly because this triggers a build on r-universe, so that you should be able to install the latest release from r-universe in a little moment.

**Comment by JanMarvin** [comment]
And just fyi: there is a little paper I once began but never finished due to leaving academia: https://github.com/JanMarvin/nlsur-paper/blob/master/Estimating-nonlinear-equationsystems-in-R-using-nlsur.pdf
This might, or might not, explain what is going on in the package 😄 Some of the arguments are a little strange iirc, like the `stata` one.

**Comment by paulaferez** [comment]
Thank you very much Marvin!
I managed to install it after installing the gfortran package (https://cran.r-project.org/bin/macosx/tools/).
Best,
